version: "3.8"

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    build:
      context: ./docker/db
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432

#   pgadmin:
#     image: dpage/pgadmin4:4.18
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${EMAIL}
#       PGADMIN_DEFAULT_PASSWORD: secret
#       PGADMIN_LISTEN_PORT: 80
#     ports:
#     - "8080:80"
#     volumes:
#     - pgadmin-data:./docker/db
#     links:
#     - "db:pgsql-server"
# volumes:
#     db-data:
#     pgadmin-data:
   